# sam3/config.py
from detectron2.config import CfgNode as CN

def add_sam3_config(cfg):

    cfg = cfg

    cfg.SEED = 3407

    cfg.MODEL.SAM3 = CN()

    cfg.MODEL.SAM3.MODEL_TYPE = "sam3_image"
    cfg.MODEL.SAM3.BPE_PATH = "sam3/assets/bpe_simple_vocab_16e6.txt.gz"
    cfg.MODEL.SAM3.USE_PE_TEXT = False
    cfg.MODEL.SAM3.USE_VILD_PROMPT = False


    cfg.MODEL.SAM3.ENABLE_SEGMENTATION = True
    cfg.MODEL.SAM3.ENABLE_INST_INTERACTIVITY = False
    cfg.MODEL.SAM3.COMPILE = False

    cfg.MODEL.SAM3.NUM_CDT = 0
    cfg.MODEL.SAM3.USE_QUERY_PROJ = False
    cfg.MODEL.SAM3.USE_PIXEL_PROJ = False
    cfg.MODEL.SAM3.USE_GATE = False
    cfg.MODEL.SAM3.ENCODER_LOSS = False
    cfg.MODEL.SAM3.DYNAMIC_QUERY = False
    cfg.MODEL.SAM3.NUM_ENCODER_QUERY = 200

    cfg.MODEL.SAM3.COS_SIM = True
    cfg.MODEL.SAM3.NEW_SCORE_HEAD = False
    cfg.MODEL.SAM3.USE_SOFTMAX = False
    cfg.MODEL.SAM3.ADD_PIXELFEAT = False
    cfg.MODEL.SAM3.USE_DOT_PROD_HEAD = False

    cfg.MODEL.SAM3.ALPHA = 0.0
    cfg.MODEL.SAM3.BETA = 0.0

    cfg.MODEL.SAM3.ORACLE_SELECT = False

    cfg.MODEL.TEACHER = None
    cfg.MODEL.TEACHER_MASKPOOL = False

    cfg.MODEL.USE_MASKADAPTER = False
    cfg.MODEL.MASKADAPTERPATH = ""

    cfg.INPUT.DATASET_MAPPER_NAME = "mask_former_semantic"
    cfg.INPUT.IMAGE_SIZE = 1008
    cfg.INPUT.COLOR_AUG_SSD = False
    cfg.INPUT.SIZE_DIVISIBILITY = -1

    cfg.INPUT.MIN_SCALE = 0.1
    cfg.INPUT.MAX_SCALE = 2.0


    cfg.MODEL.PIXEL_MEAN = [127.5, 127.5, 127.5]
    cfg.MODEL.PIXEL_STD = [127.5, 127.5, 127.5]

    cfg.SOLVER.WEIGHT_DECAY_EMBED = 0.0
    # optimizer
    cfg.SOLVER.OPTIMIZER = "ADAMW"
    cfg.SOLVER.BACKBONE_MULTIPLIER = 0.1
    cfg.SOLVER.NO_OBJECT_WEIGHT = 0.1
    cfg.SOLVER.CLASS_WEIGHT = 2.0
    cfg.SOLVER.CONTRAST_WEIGHT = 0.0
    cfg.SOLVER.OBJECT_WEIGHT = 2.0
    cfg.SOLVER.MASK_WEIGHT = 5.0
    cfg.SOLVER.DICE_WEIGHT = 5.0
    cfg.SOLVER.BBOX_WEIGHT = 5.0
    cfg.SOLVER.GIOU_WEIGHT = 2.0
    cfg.SOLVER.TRAIN_NUM_POINTS = 12544
    cfg.SOLVER.OVERSAMPLE_RATIO = 3.0
    cfg.SOLVER.IMPORTANCE_SAMPLE_RATIO = 0.75

    cfg.SOLVER.USE_AUX = True
    cfg.SOLVER.CLIP_DISTILL = False
    cfg.SOLVER.CONTRAST_TEMPERATURE = 0.07

    cfg.SOLVER.TRAIN_MASK = True
    cfg.SOLVER.TRAIN_OUT_VOCAB = False

    cfg.TEST.SEMANTIC_ON = True
    cfg.TEST.INSTANCE_ON = False
    cfg.TEST.PANOPTIC_ON = False
    cfg.TEST.DETECTIONS_PER_IMAGE = 100

    cfg.DATALOADER.DATASET_RATIO = [1.0]
    cfg.DATALOADER.USE_DIFF_BS_SIZE = False
    cfg.DATALOADER.DATASET_BS = [2]
    cfg.DATALOADER.USE_RFS = [False]
    cfg.DATALOADER.DATASET_ANN = ["box"]
    cfg.DATALOADER.MULTI_DATASET_GROUPING = True

    cfg.DATASETS.ONLY_INSTANCE = False

    cfg.MODEL.MASK_ADAPTER = CN()
    cfg.MODEL.MASK_ADAPTER.NAME = "MASKAdapterHead"
    cfg.MODEL.MASK_ADAPTER.FEAT_DIM = 1024
    cfg.MODEL.MASK_ADAPTER.MASK_IN_CHANNELS = 16
    cfg.MODEL.MASK_ADAPTER.NUM_CHANNELS = 768
    cfg.MODEL.MASK_ADAPTER.USE_CHECKPOINT = False
    cfg.MODEL.MASK_ADAPTER.NUM_OUTPUT_MAPS = 16

    cfg.MODEL.MASK_ADAPTER.IOU_THRESHOLD = 0.7
    cfg.MODEL.MASK_ADAPTER.MASK_THRESHOLD  = 0.50
    cfg.MODEL.MASK_ADAPTER.TRAIN_MAFT = False
    cfg.MODEL.MASK_ADAPTER.COS_WEIGHT = 5.0
    cfg.MODEL.MASK_ADAPTER.CLASS_WEIGHT = 2.0
    cfg.MODEL.MASK_ADAPTER.NUM_GT_MASKS = 16
    cfg.MODEL.MASK_ADAPTER.NUM_PRED_MASKS = 8

    cfg.MODEL.ATTNPOOL = CN()
    cfg.MODEL.ATTNPOOL.ENABLE = False
    cfg.MODEL.ATTNPOOL.USE_AUX = True
    cfg.MODEL.ATTNPOOL.CLASS_WEIGHT = 1.0
    cfg.MODEL.ATTNPOOL.NUM_GT_MASKS = 16
    cfg.MODEL.ATTNPOOL.NUM_PRED_MASKS = 8
    cfg.MODEL.ATTNPOOL.IOU_THRESHOLD = 0.7
    cfg.MODEL.ATTNPOOL.ADD_RADIO_FEAT = False
    cfg.MODEL.ATTNPOOL.NEW_POOL_DECODER = False
    cfg.MODEL.ATTNPOOL.BUILD_POOL_DECODER_FROM_MASKDECODER = False

    cfg.MODEL.MAP_ADAPTER = CN()
    cfg.MODEL.MAP_ADAPTER.ENABLE = False
    cfg.MODEL.MAP_ADAPTER.NAME = "MAP_ADAPTER"
    cfg.MODEL.MAP_ADAPTER.FEAT_DIM = 4096
    cfg.MODEL.MAP_ADAPTER.NUM_ATTN_MAPS = 9
    cfg.MODEL.MAP_ADAPTER.MASK_IN_CHANNELS = 16
    cfg.MODEL.MAP_ADAPTER.NUM_CHANNELS = 768
    cfg.MODEL.MAP_ADAPTER.USE_CHECKPOINT = False
    cfg.MODEL.MAP_ADAPTER.NUM_OUTPUT_MAPS = 16
    cfg.MODEL.MAP_ADAPTER.CHUNK_SIZE = 0
    cfg.MODEL.MAP_ADAPTER.TRAIN_ONLY = False

    cfg.MODEL.VPT = CN()
    cfg.MODEL.VPT.ENABLE = False
    cfg.MODEL.VPT.GRAD_CHECKPOINT = False
    cfg.MODEL.VPT.NUM_PROMPTS_TO_INSERT = 5
    cfg.MODEL.VPT.START_LAYER = 1
    cfg.MODEL.VPT.END_LAYER = -1
