import { useMemo } from 'react';
import type {
  AllPrompts, AllPrograms, SelectedProgramItem, ProgramData,
  TagGroup, LoraItemData, LoraSelectionData, SelectedPrefabItem, AllLibraries,
} from '../types';
import { tagsToDisplayString, parseStringToTags } from './useSelection';

function toList(v: string | string[] | undefined): string[] {
  if (Array.isArray(v)) return v;
  if (typeof v === 'string') return v.split(',').map(s => s.trim()).filter(Boolean);
  return [];
}

/** Build the all_tags lookup table from allPrompts (category + per-prompt decorations/tags/mute_decorations). */
export function buildAllTagsLookup(allPrompts: AllPrompts): Record<string, { name: string; prompt: string; category: string; decorations: string[]; tags: string[]; mute_decorations: string[] }> {
  const allTags: Record<string, { name: string; prompt: string; category: string; decorations: string[]; tags: string[]; mute_decorations: string[] }> = {};
  for (const [cat, catData] of Object.entries(allPrompts)) {
    const cd = catData as any;
    const catDecos = toList(cd.decorations).map(d => d.toLowerCase());
    const catTags = toList(cd.tags).map(t => t.toLowerCase());
    const prompts: any[] = cd.prompts || [];
    for (const p of prompts) {
      if (!p.prompt) continue;
      const key = p.prompt.toLowerCase();
      const pDecos = toList(p.decorations).map(d => d.toLowerCase());
      const pTags = toList(p.tags).map(t => t.toLowerCase());
      const pMute = toList(p.mute_decorations).map(d => d.toLowerCase());
      allTags[key] = {
        name: p.name || p.prompt,
        prompt: p.prompt,
        category: cat,
        decorations: [...new Set([...catDecos, ...pDecos])],
        tags: [...new Set([...catTags, ...pTags])],
        mute_decorations: pMute,
      };
    }
  }
  return allTags;
}

/** Enrich tag_groups with decorations + tags from the all_tags lookup table. */
export function enrichTagGroups(selectedTags: TagGroup[], allTagsLookup: Record<string, { decorations: string[]; tags: string[] }>): TagGroup[] {
  return selectedTags.map(g => ({
    ...g,
    tags: g.tags.map(t => {
      const info = allTagsLookup[t.prompt.toLowerCase()];
      return {
        ...t,
        decorations: info?.decorations || [],
        tags: info?.tags || [],
      };
    }),
  }));
}

/** Build LoraSelectionData[] from selected loras + their selection state. */
export function buildLoraSelectionData(
  selectedLoras: LoraItemData[],
  loraSelections: Record<string, { activeTags: string[]; strength: number; active: boolean; split_mode?: boolean }>,
): LoraSelectionData[] {
  return selectedLoras.map(l => {
    const sel = loraSelections[l.file_path];
    return { file_path: l.file_path, name: l.name, strength: sel?.strength ?? 1.0, active_tags: sel?.activeTags ?? [], active: sel?.active ?? true, split_mode: sel?.split_mode };
  });
}

export interface ProgramResult {
  // Final combined output (original minus filtered + generated)
  resultTags: TagGroup[];
  resultLoras: LoraSelectionData[];
  resultPrefabs: any[];
  resultCustomPrompts: string;
  // Items filtered out by programs (dimmed in UI)
  filter_tag_groups: TagGroup[];
  filter_loras: LoraSelectionData[];
  filter_prefabs: any[];
  // Items generated by programs (cyan glow in UI)
  gen_tag_groups: TagGroup[];
  gen_loras: LoraSelectionData[];
  gen_prefabs: any[];
}

export function useProgram(
  selectedPrograms: SelectedProgramItem[],
  allPrograms: AllPrograms,
  selectedTags: TagGroup[],
  selectedLoras: LoraItemData[],
  loraSelections: Record<string, { activeTags: string[]; strength: number; active: boolean; split_mode?: boolean }>,
  selectedPrefabs: SelectedPrefabItem[],
  customPrompts: string,
  allPrompts: AllPrompts,
  allLibraries: AllLibraries,
  allLoraData: Record<string, LoraItemData[]>,
): ProgramResult {
  return useMemo(() => {
    // Build a lookup of all programs by id
    const programById = new Map<string, ProgramData>();
    for (const catData of Object.values(allPrograms)) {
      for (const app of (catData.programs || [])) {
        programById.set(app.id, app);
      }
    }

    // Collect active programs in order, resolving sub-programs recursively
    // Each entry carries its own context source (SelectedProgramItem / SelectedProgramRef)
    interface ActiveProgram {
      code: string;
      name: string;
      ctxSource?: {
        context_prefab_guids?: string[];
        context_lora_paths?: string[];
        context_prompt_texts?: string[];
        context_prefab_inactive?: string[];
        context_lora_inactive?: string[];
        context_prompt_inactive?: string[];
        enable_prefab_context?: boolean;
        enable_lora_context?: boolean;
        enable_prompt_context?: boolean;
        prefab_builtin_guids?: string[];
        lora_builtin_paths?: string[];
        tag_group_builtin_texts?: string[];
        prefab_builtin_inactive?: string[];
        lora_builtin_inactive?: string[];
        tag_group_builtin_inactive?: string[];
      };
    }
    const activePrograms: ActiveProgram[] = [];
    const resolved = new Set<string>();
    function resolvePrograms(items: { id: string; context_prefab_guids?: string[]; context_lora_paths?: string[]; context_prompt_texts?: string[]; context_prefab_inactive?: string[]; context_lora_inactive?: string[]; context_prompt_inactive?: string[] }[], depth = 0, inheritedCtx?: ActiveProgram['ctxSource']) {
      for (const item of items) {
        const pid = item.id;
        if (resolved.has(pid)) continue;
        resolved.add(pid);
        const app = programById.get(pid);
        if (!app) continue;
        // Build this program's context source: own instance data + program definition toggles + builtin (shared)
        const ctxSource: ActiveProgram['ctxSource'] = {
          context_prefab_guids: item.context_prefab_guids,
          context_lora_paths: item.context_lora_paths,
          context_prompt_texts: item.context_prompt_texts,
          context_prefab_inactive: item.context_prefab_inactive,
          context_lora_inactive: item.context_lora_inactive,
          context_prompt_inactive: item.context_prompt_inactive,
          enable_prefab_context: app.enable_prefab_context,
          enable_lora_context: app.enable_lora_context,
          enable_prompt_context: app.enable_prompt_context,
          prefab_builtin_guids: app.prefab_builtin_guids,
          lora_builtin_paths: app.lora_builtin_paths,
          tag_group_builtin_texts: app.tag_group_builtin_texts,
          prefab_builtin_inactive: app.prefab_builtin_inactive,
          lora_builtin_inactive: app.lora_builtin_inactive,
          tag_group_builtin_inactive: app.tag_group_builtin_inactive,
        };
        // Execute sub-programs first (recursive) — even if parent has no code
        const subPrograms = (app.selected_programs || []).filter(sp => sp.active !== false);
        if (subPrograms.length > 0) {
          // Sub-programs inherit parent's context (use parent's ctxSource if sub-program has no own context data)
          resolvePrograms(subPrograms.map(sp => ({
            id: sp.id,
            context_prefab_guids: sp.context_prefab_guids ?? ctxSource.context_prefab_guids,
            context_lora_paths: sp.context_lora_paths ?? ctxSource.context_lora_paths,
            context_prompt_texts: sp.context_prompt_texts ?? ctxSource.context_prompt_texts,
            context_prefab_inactive: sp.context_prefab_inactive ?? ctxSource.context_prefab_inactive,
            context_lora_inactive: sp.context_lora_inactive ?? ctxSource.context_lora_inactive,
            context_prompt_inactive: sp.context_prompt_inactive ?? ctxSource.context_prompt_inactive,
          })), depth + 1, ctxSource);
        }
        // Only add to execution list if this program has actual code
        if (app.code && app.code.trim()) {
          activePrograms.push({ code: app.code, name: app.name, ctxSource });
        }
      }
    }
    // Debug: log selected programs and programById
    console.log('[useProgram] selectedPrograms:', JSON.stringify(selectedPrograms));
    console.log('[useProgram] programById keys:', [...programById.keys()]);
    console.log('[useProgram] allPrograms keys:', Object.keys(allPrograms));

    for (const sa of selectedPrograms) {
      if (!sa.active) continue;
      resolvePrograms([sa], 0);
    }

    // Debug: log resolved program chain
    console.log('[useProgram] activePrograms count:', activePrograms.length);
    if (activePrograms.length > 0) {
      console.log('[useProgram] Resolved program chain:', activePrograms.map((p, i) => `${i}:${p.name}`));
    }

    const noProgramsResult: ProgramResult = {
      resultTags: selectedTags.filter(g => g.source !== 'program'),
      resultLoras: buildLoraSelectionData(selectedLoras.filter(l => (l as any).source !== 'program'), loraSelections),
      resultPrefabs: selectedPrefabs.filter(p => (p as any).source !== 'program'),
      resultCustomPrompts: customPrompts,
      filter_tag_groups: [],
      filter_loras: [],
      filter_prefabs: [],
      gen_tag_groups: [],
      gen_loras: [],
      gen_prefabs: [],
    };

    if (activePrograms.length === 0) {
      return noProgramsResult;
    }

    // Build all_tags from allPrompts
    const allTags = buildAllTagsLookup(allPrompts);

    // Strip program-sourced items from the previous run so they don't accumulate
    const baseTags = selectedTags.filter(g => g.source !== 'program');
    const baseLoras = selectedLoras.filter(l => (l as any).source !== 'program');
    const basePrefabs = selectedPrefabs.filter(p => (p as any).source !== 'program');

    // Build context — enrich each Tag with decorations and tags from allTags
    let ctxTags: TagGroup[] = enrichTagGroups(baseTags, allTags);
    let ctxLoras: LoraSelectionData[] = buildLoraSelectionData(baseLoras, loraSelections);
    // Build guid → PrefabData lookup
    const prefabDataMap = new Map<string, any>();
    for (const libData of Object.values(allLibraries)) {
      for (const pf of (libData.prefabs || [])) {
        if (pf.guid) prefabDataMap.set(pf.guid, pf);
      }
    }

    // Build merged prefab data: selection state + actual tags/loras/custom_prompts
    const buildMergedPrefab = (item: SelectedPrefabItem): any => {
      const pfData = prefabDataMap.get(item.guid);
      return {
        guid: item.guid,
        active: item.active,
        // Selection state: which tag groups / loras are active
        tag_states: item.tag_groups.map(t => ({ ...t })),
        lora_states: item.loras.map(l => ({ ...l })),
        // Actual data from prefab definition
        name: pfData?.name || '',
        tag_groups: pfData?.tag_groups ? pfData.tag_groups.map((g: any) => ({ ...g, tags: g.tags ? g.tags.map((t: any) => ({ ...t })) : g.map((t: any) => ({ ...t })) })) : [],
        loras: pfData?.loras ? pfData.loras.map((l: any) => ({ ...l })) : [],
        custom_prompts: pfData?.custom_prompts || '',
        preview: pfData?.preview || '',
        children: item.children.map(c => buildMergedPrefab(c)),
      };
    };
    let ctxPrefabs: any[] = basePrefabs.map(p => buildMergedPrefab(p));
    let ctxCustomPrompts = customPrompts;

    // Accumulators: collect all filters and gens from all programs, apply at end
    const allFilterTags: any[] = [];
    const allFilterLoras: any[] = [];
    const allFilterPrefabs: any[] = [];
    const allGenTags: any[] = [];
    const allGenLoras: any[] = [];
    const allGenPrefabs: any[] = [];

    // Build lora lookup (shared across all programs)
    const loraLookup = new Map<string, LoraItemData>();
    for (const items of Object.values(allLoraData)) { for (const item of items) loraLookup.set(item.file_path, item); }

    // Run each program
    for (const prog of activePrograms) {
      // Build context variables from THIS program's own context source
      const cs = prog.ctxSource;
      let prefabContext: any[] = [];
      let loraContext: LoraSelectionData[] = [];
      let promptContext: TagGroup[] = [];
      let prefabBuiltin: any[] = [];
      let loraBuiltin: LoraSelectionData[] = [];
      let tagGroupBuiltin: TagGroup[] = [];

      if (cs) {
        if (cs.enable_prefab_context && cs.context_prefab_guids) {
          prefabContext = cs.context_prefab_guids.map((guid: string) => {
            const pfData = prefabDataMap.get(guid);
            if (!pfData) return null;
            const isActive = !(cs.context_prefab_inactive || []).includes(guid);
            return { guid, name: pfData.name || '', tag_groups: pfData.tag_groups || [], loras: pfData.loras || [], custom_prompts: pfData.custom_prompts || '', preview: pfData.preview || '', active: isActive };
          }).filter(Boolean);
        }
        if (cs.enable_lora_context && cs.context_lora_paths) {
          loraContext = cs.context_lora_paths.map((fp: string) => {
            const item = loraLookup.get(fp);
            if (!item) return null;
            const isActive = !(cs.context_lora_inactive || []).includes(fp);
            const sel = loraSelections[fp];
            return { file_path: fp, name: item.name, strength: sel?.strength ?? 1.0, active_tags: sel?.activeTags ?? item.tags ?? [], active: isActive, split_mode: sel?.split_mode };
          }).filter(Boolean) as LoraSelectionData[];
        }
        if (cs.enable_prompt_context && cs.context_prompt_texts) {
          promptContext = cs.context_prompt_texts.map((text: string) => {
            const isActive = !(cs.context_prompt_inactive || []).includes(text);
            const tg = parseStringToTags(text, allPrompts);
            return { ...tg, active: isActive };
          });
        }
        // Builtin (shared data from program definition, no enable toggle needed)
        if (cs.prefab_builtin_guids) {
          prefabBuiltin = cs.prefab_builtin_guids.map((guid: string) => {
            const pfData = prefabDataMap.get(guid);
            if (!pfData) return null;
            const isActive = !(cs.prefab_builtin_inactive || []).includes(guid);
            return { guid, name: pfData.name || '', tag_groups: pfData.tag_groups || [], loras: pfData.loras || [], custom_prompts: pfData.custom_prompts || '', preview: pfData.preview || '', active: isActive };
          }).filter(Boolean);
        }
        if (cs.lora_builtin_paths) {
          loraBuiltin = cs.lora_builtin_paths.map((fp: string) => {
            const item = loraLookup.get(fp);
            if (!item) return null;
            const isActive = !(cs.lora_builtin_inactive || []).includes(fp);
            const sel = loraSelections[fp];
            return { file_path: fp, name: item.name, strength: sel?.strength ?? 1.0, active_tags: sel?.activeTags ?? item.tags ?? [], active: isActive, split_mode: sel?.split_mode };
          }).filter(Boolean) as LoraSelectionData[];
        }
        if (cs.tag_group_builtin_texts) {
          tagGroupBuiltin = cs.tag_group_builtin_texts.map((text: string) => {
            const isActive = !(cs.tag_group_builtin_inactive || []).includes(text);
            const tg = parseStringToTags(text, allPrompts);
            return { ...tg, active: isActive };
          });
        }
      }

      try {
        const fn = new Function(
          'tag_groups', 'loras', 'prefabs', 'custom_prompts', 'prompts_data', 'all_tags',
          'prefab_context', 'lora_context', 'prompt_context',
          'prefab_builtin', 'lora_builtin', 'tag_group_builtin',
          prog.code,
        );
        const result = fn(
          ctxTags.map(g => ({ ...g, tags: g.tags.map(t => ({ ...t, decorations: t.decorations ? [...t.decorations] : [], tags: t.tags ? [...t.tags] : [] })) })),
          ctxLoras.map(l => ({ ...l })),
          ctxPrefabs.map(p => ({
            ...p,
            tag_groups: p.tag_groups ? p.tag_groups.map((g: any) => ({ ...g, tags: g.tags ? g.tags.map((t: any) => ({ ...t })) : [] })) : [],
            loras: p.loras ? p.loras.map((l: any) => ({ ...l })) : [],
            tag_states: p.tag_states ? p.tag_states.map((t: any) => ({ ...t })) : [],
            lora_states: p.lora_states ? p.lora_states.map((l: any) => ({ ...l })) : [],
            children: p.children ? p.children.map((c: any) => ({ ...c })) : [],
          })),
          ctxCustomPrompts,
          allPrompts,
          allTags,
          prefabContext,
          loraContext,
          promptContext,
          prefabBuiltin,
          loraBuiltin,
          tagGroupBuiltin,
        );
        if (result && typeof result === 'object') {
          // Collect filters and gens into accumulators (applied after all programs run)
          if (Array.isArray(result.filter_tag_groups)) {
            allFilterTags.push(...result.filter_tag_groups);
          }
          if (Array.isArray(result.filter_loras)) {
            allFilterLoras.push(...result.filter_loras);
          }
          if (Array.isArray(result.filter_prefabs)) {
            allFilterPrefabs.push(...result.filter_prefabs);
          }
          if (Array.isArray(result.gen_tag_groups)) {
            allGenTags.push(...result.gen_tag_groups);
          }
          if (Array.isArray(result.gen_loras)) {
            allGenLoras.push(...result.gen_loras);
          }
          if (Array.isArray(result.gen_prefabs)) {
            allGenPrefabs.push(...result.gen_prefabs);
          }
          if (typeof result.custom_prompts === 'string') ctxCustomPrompts = result.custom_prompts;
        }
      } catch (e) {
        console.error(`[Program] Error in '${prog.name}':`, e);
      }
    }

    // Apply all accumulated filters and gens at once
    const filterTagKeys = new Set(allFilterTags.map(g => tagsToDisplayString(g)));
    ctxTags = ctxTags.filter(g => !filterTagKeys.has(tagsToDisplayString(g)));
    ctxTags = [...ctxTags, ...allGenTags.map(g => ({ ...g, source: 'program' as const }))];

    const filterLoraPaths = new Set(allFilterLoras.map(l => l.file_path));
    ctxLoras = ctxLoras.filter(l => !filterLoraPaths.has(l.file_path));
    ctxLoras = [...ctxLoras, ...allGenLoras.map(l => ({ ...l, source: 'program' as const }))];

    const filterPrefabGuids = new Set(allFilterPrefabs.map(p => p.guid));
    ctxPrefabs = ctxPrefabs.filter(p => !filterPrefabGuids.has(p.guid));
    ctxPrefabs = [...ctxPrefabs, ...allGenPrefabs.map(p => ({ ...p, source: 'program' as const }))];

    // Compute filtered (removed) and generated (added) sets
    // Compare against base* (without program-sourced items from previous run)
    const originalTagKeys = new Set(baseTags.map(g => tagsToDisplayString(g)));
    const resultTagKeys = new Set(ctxTags.map(g => tagsToDisplayString(g)));
    const filter_tag_groups = baseTags.filter(g => !resultTagKeys.has(tagsToDisplayString(g)));
    const gen_tag_groups = ctxTags.filter(g => !originalTagKeys.has(tagsToDisplayString(g)));

    const originalLoraPaths = new Set(baseLoras.map(l => l.file_path));
    const resultLoraPaths = new Set(ctxLoras.map(l => l.file_path));
    const filter_loras = buildLoraSelectionData(baseLoras.filter(l => !resultLoraPaths.has(l.file_path)), loraSelections);
    const gen_loras = ctxLoras.filter(l => !originalLoraPaths.has(l.file_path));

    const originalPrefabGuids = new Set(basePrefabs.map(p => p.guid));
    const resultPrefabGuids = new Set(ctxPrefabs.map(p => p.guid));
    const filter_prefabs = basePrefabs.filter(p => !resultPrefabGuids.has(p.guid));
    const gen_prefabs = ctxPrefabs.filter(p => !originalPrefabGuids.has(p.guid));

    return {
      resultTags: ctxTags,
      resultLoras: ctxLoras,
      resultPrefabs: ctxPrefabs,
      resultCustomPrompts: ctxCustomPrompts,
      filter_tag_groups,
      filter_loras,
      filter_prefabs,
      gen_tag_groups,
      gen_loras,
      gen_prefabs,
    };
  }, [selectedPrograms, allPrograms, selectedTags, selectedLoras, loraSelections, selectedPrefabs, customPrompts, allPrompts, allLibraries, allLoraData]);
}
